export const allSubjects = [
  "Arts",
  "Biology",
  "Chemistry",
  "ComputerScience",
  "Economics",
  "English",
  "Geography",
  "History",
  "Mathematics",
  "Music",
  "Philosophy",
  "PhysicalEducation",
  "Physics",
  "PoliticalScience",
  "Psychology",
  "Sociology",
];

export enum Subject {
  Arts = "美術",
  Biology = "生物学",
  Chemistry = "化学",
  ComputerScience = "情報科学",
  Economics = "経済学",
  English = "英語",
  Geography = "地理",
  History = "歴史",
  Mathematics = "数学",
  Music = "音楽",
  Philosophy = "哲学",
  PhysicalEducation = "体育",
  Physics = "物理学",
  PoliticalScience = "政治学",
  Psychology = "心理学",
  Sociology = "社会学",
}
